name = "hsc-notes-by-siam"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[pages]
main = "./"

[build]
command = "npm run build:cf"
build_output_dir = ".vercel/output/static"
